### ISSUE TITLE
Result imgs info

### ISSUE THREAD

**Issue by AilinJ** [xulabs/aitom_doc#3]
For easier comparison, should we provide some relevant information about the result images? For example, the z value of the particle-picking result image.

**Comment by xulabs** [comment]
@AilinJ yes, please go ahead to make the improvements

**Comment by AilinJ** [comment]
@xulabs I actually got a seemingly different result from the particle_picking_result.png (mine shows more peaks), could @wobushiyitouzhu add the info (z-value, if it has been processed...) for this particular image?

**Comment by xulabs** [comment]
@AilinJ @wobushiyitouzhu please work together on this issue thanks.

**Comment by wobushiyitouzhu** [comment]
@ijinjay 'particle_picking_result.png' is the result under such conditions:
1 'sigma1' is 5 rather than 3 for better performance(in this tomogram, 7nm corresponds to 3.84 pixels)
2 'FG.dog_smooth' rather than 'FG.dog_smooth__large_map' is used in line 91 of https://github.com/xulabs/aitom/blob/master/aitom/pick/dog/particle_picking_dog__util.py. The latter leads to much more peaks.
3 'partition_op' is 'None' when getting this result (3370 peaks). Set 'partition_op' leads to more peaks (4140 peaks detected). 
4 'z-value' is not recorded. For rough comparison, the number of detected peaks can be compared with 3.  If more accurate comparisons are needed, I can upload 'data_json_file.json' which contains coordinates of all detected peaks.

**Comment by xulabs** [comment]
Please clarify in the tutorial if needed.

Please do not add data to repository. We need to keep the repository slim.

**Comment by wobushiyitouzhu** [comment]
@xulabs Comments have been added in the tutorial and the relevant code in AITom has also been modified. 
@AilinJ  Please try again the updated project to see if there are any problems.
